spring:
  jpa:
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  # profiles:
  #   active: pyk

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

---

spring:
  config:
    activate:
      on-profile: hyun

  datasource:
    url: jdbc:mariadb://20.78.149.80:3306/iac_platform-test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 211224

  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: lichee55

  datasource:
    url: jdbc:mariadb://localhost:3306/testcontainer?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  config:
    activate:
      on-profile: kgh

  datasource:
    url: jdbc:mariadb://localhost:3307/iac_platform?characterEncoding=UTF-8&serverTimezone=UTC
    username: guest
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: pyk

  datasource:
    url: jdbc:mariadb://localhost:3307/iac_platform?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
